title: 7842B Journal
email: theol0403@gmail.com
description: >-
  7842B Digital Build & Programming Journal

baseurl: ""
url: ""

theme: just-the-docs

ignore_theme_config: true
color_scheme: "dark"
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
footer_content: "Copyright &copy; 2020-2021"

permalink: /:categories/:year-:month-:day/:title/

aux_links:
  "Build": "/build"
  "Programming": "/programming"

defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_posts/build"
    values:
      grand_parent: Build
      author: Saywer McClellan
  - scope:
      path: "_posts/programming"
    values:
      grand_parent: Programming
      author: Theo Lemay
  - scope:
      path: "pages/programming"
    values:
      author: Theo Lemay
