title: 7842F Journal
email: theol0403@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  7842F Programming Journal, Showcase, and Documentation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://theol0403.github.io/7842F-Programming-Journal" # the base hostname & protocol for your site, e.g. http://example.com
images_url: "https://theol0403.github.io/7842F-Programming-Journal/assets/images" # the base hostname & protocol for your site, e.g. http://example.com
github_username: theol0403

remote_theme: theol0403/just-the-docs

# Just the docs
color_scheme: "dark"
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
footer_content: "Copyright &copy; 2019-2020 Theo Lemay"
aux_links:
  "lib7842": "//github.com/theol0403/lib7842"
  "Tower": "//github.com/theol0403/7842F-Tower-Code"
  "Github": "//github.com/theol0403/7842F-Programming-Journal"

permalink: /:categories/:year-:month-:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      grand_parent: All Posts
