title: 7842B Journal
email: theol0403@gmail.com
description: >-
  7842B 2020/2021 Digital Build & Programming Journal

baseurl: ""
url: "https://theol0403.github.io/7842B-Journal"
images_url: "https://theol0403.github.io/7842B-Journal/assets/images"

github_username: theol0403
remote_theme: theol0403/just-the-docs

# Just the docs
color_scheme: "dark"
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
footer_content: "Copyright &copy; 2020-2021"
aux_links:

permalink: /:categories/:year-:month-:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      grand_parent: All Posts
